using JuMP, HiGHS

model = Model(HiGHS.Optimizer)

# DEGENERATED:
# @variable(model, x[1:10]) 
# @constraint(model, x[1] + x[2] <= 0)
# @constraint(model, x[1] + x[3] <= 0)
# @constraint(model, x[1] + x[4] <= 0)
# @constraint(model, x[1] + x[5] <= 0)
# @constraint(model, x[1] + x[6] <= 0)
# @constraint(model, x[1] + x[7] <= 0)
# @constraint(model, x[1] + x[8] <= 0)
# @constraint(model, x[1] + x[9] <= 0)
# @constraint(model, x[1] + x[10] <= 0)
# @constraint(model, x[2] + x[3] <= 0)
# @constraint(model, x[2] + x[4] <= 0)
# @constraint(model, x[2] + x[5] <= 0)
# @constraint(model, x[2] + x[6] <= 0)
# @constraint(model, x[2] + x[7] <= 0)
# @constraint(model, x[2] + x[8] <= 0)
# @constraint(model, x[2] + x[9] <= 0)
# @constraint(model, x[2] + x[10] <= 0)
# @constraint(model, x[3] + x[4] <= 0)
# @constraint(model, x[3] + x[5] <= 0)
# @constraint(model, x[3] + x[6] <= 0)
# @constraint(model, x[3] + x[7] <= 0)
# @constraint(model, x[3] + x[8] <= 0)
# @constraint(model, x[3] + x[9] <= 0)
# @constraint(model, x[3] + x[10] <= 0)
# @constraint(model, x[4] + x[5] <= 0)
# @constraint(model, x[4] + x[6] <= 0)
# @constraint(model, x[4] + x[7] <= 0)
# @constraint(model, x[4] + x[8] <= 0)
# @constraint(model, x[4] + x[9] <= 0)
# @constraint(model, x[4] + x[10] <= 0)
# @constraint(model, x[5] + x[6] <= 0)
# @constraint(model, x[5] + x[7] <= 0)
# @constraint(model, x[5] + x[8] <= 0)
# @constraint(model, x[5] + x[9] <= 0)
# @constraint(model, x[5] + x[10] <= 0)
# @constraint(model, x[6] + x[7] <= 0)
# @constraint(model, x[6] + x[8] <= 0)
# @constraint(model, x[6] + x[9] <= 0)
# @constraint(model, x[6] + x[10] <= 0)
# @constraint(model, x[7] + x[8] <= 0)
# @constraint(model, x[7] + x[9] <= 0)
# @constraint(model, x[7] + x[10] <= 0)
# @constraint(model, x[8] + x[9] <= 0)
# @constraint(model, x[8] + x[10] <= 0)
# @constraint(model, x[9] + x[10] <= 0)
# @objective(model, Min, sum(x))


# FEASIBLE 1:
@variable(model, x[1:10]) 
@constraint(model, x[1] <= 1)
@constraint(model, x[1] >= 0)
@constraint(model, x[2] <= 1)
@constraint(model, x[2] >= 0)
@constraint(model, x[2] + x[1] <= 1)
@constraint(model, x[3] <= 1)
@constraint(model, x[3] >= 0)
@constraint(model, x[3] + x[1] <= 1)
@constraint(model, x[4] <= 1)
@constraint(model, x[4] >= 0)
@constraint(model, x[4] + x[1] <= 1)
@constraint(model, x[5] <= 1)
@constraint(model, x[5] >= 0)
@constraint(model, x[5] + x[1] <= 1)
@constraint(model, x[6] <= 1)
@constraint(model, x[6] >= 0)
@constraint(model, x[6] + x[1] <= 1)
@constraint(model, x[7] <= 1)
@constraint(model, x[7] >= 0)
@constraint(model, x[7] + x[1] <= 1)
@constraint(model, x[8] <= 1)
@constraint(model, x[8] >= 0)
@constraint(model, x[8] + x[1] <= 1)
@constraint(model, x[9] <= 1)
@constraint(model, x[9] >= 0)
@constraint(model, x[9] + x[1] <= 1)
@constraint(model, x[10] <= 1)
@constraint(model, x[10] >= 0)
@constraint(model, x[10] + x[1] <= 1)
@objective(model, Max, sum(x))

optimize!(model)
